const projectConstants = {
    FETCH_ALL_RESOURCES_BY_PROJECT_SUCCESS: "FETCH_ALL_RESOURCES_BY_PROJECT_SUCCESS", 
    FETCH_ALL_RESOURCES_BY_PROJECT_FAILURE: "FETCH_ALL_RESOURCES_BY_PROJECT_FAILURE",
    SEND_SELECTED_RESOURCES_TO_PRJECTS_RIGHT_TABLE: "SEND_SELECTED_RESOURCES_TO_PRJECTS_RIGHT_TABLE"
}


export default projectConstants;