const resourceConstants = {
    FETCH_ALL_RESOURCES: 'FETCH_ALL_RESOURCES',
        
    ADD_COLUMN_SUCCESS: 'ADD_COLUMN_SUCCESS', 
    ADD_COLUMN_FAILURE: 'ADD_COLUMN_FAILURE', 

    ADD_ROW_SUCCESS: "ADD_ROW_SUCCESS", 
    ADD_ROW_FAILURE: "ADD_ROW_FAILURE", 

    ADD_MANY_COL_SUCCESS: 'ADD_MANY_COL_SUCCESS', 
    ADD_MANY_COL_FAILURE: 'ADD_MANY_COL_FAILURE',
    ADD_MANY_ROW_SUCCESS: 'ADD_MANY_ROW_SUCCESS', 
    ADD_MANY_ROW_FAILURE: 'ADD_MANY_ROW_FAILURE'
};

export default resourceConstants